include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: ['**/**.g.dart', '**/**gr.dart','**/**.freezed.dart', 'lib/l10n/gen/*']
linter:
  rules:
    sort_pub_dependencies: false
    sort_constructors_first: false
    document_ignores: false
